DIV-6645: Add content for Served by alternative method
hmcts/div-decree-nisi-frontend pull request #506
Opened 2020-11-30 17:57 UTC by jacmurphy

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:

* Hardware:
* O/S and version:
* JDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-01 15:12 UTC, jacmurphy commented on helpers/petitionHelper.js
> +  return isServedByProcessServer(caseData) && !hasReceivedAosFromRespondent(caseData);
Small naming improvement

2020-12-01 15:28 UTC, jacmurphy commented on helpers/petitionHelper.js
> +};
This is the logic that determines if this flow works. I tried to make it as readable as possible.

I wanted to leave a comment in here highlighting that the precondition of having the state be "AwaitingDecreeNisi" has already been validated by this point, and thus, does not need explicit reference here.

I initially had it included, but it caused an issue where there had to be a differenciate between the CaseState and the CaseData.

2020-12-01 15:30 UTC, jacmurphy commented on helpers/petitionHelper.js
> +  isReceivedAosFromRespondent: hasReceivedAosFromRespondent,
Add a more readable alias

2020-12-01 15:31 UTC, jacmurphy commented on mocks/steps/modify-session/ModifySession.content.json
> +        },
Content of button that will allow this to be manipulated in "/session"

2020-12-01 15:31 UTC, jacmurphy commented on mocks/steps/modify-session/sections/petitioner.html
> +  ) }}
html that renders the content to allow local testing

2020-12-01 15:51 UTC, jacmurphy commented on steps/petition-progress-bar/sections/servedByAlternativeMethod/PetitionProgressBar.content.servedByAlternativeMethod.json
> +}
Requires welsh translation (out of scope)

2020-12-01 15:55 UTC, jacmurphy commented on steps/petition-progress-bar/sections/undefended/PetitionProgressBar.undefended.template.html
> +})
Autoformatting was not correct. Will revert this change

2020-12-03 10:42 UTC, Dizrupto commented on helpers/petitionHelper.js
> +};
Yep you're right, the state has already been validated by this point so you don't need to add more logic for the state here :)

2020-12-04 09:11 UTC, Dizrupto approved these changes

2020-12-04 10:13 UTC, madjava commented on helpers/petitionHelper.js
> +  isReceivedAosFromRespondent: hasReceivedAosFromRespondent,
Hey Jack, you can ignore Intellij trying to be helpful here and leave is as `isReceivedAosFromRespondent` as per code naming standards if a function returns a boolean it starts with a `is` would be nice if we maintain same

2020-12-04 10:13 UTC, madjava commented on helpers/petitionHelper.js
> +  return isServedByProcessServer(caseData) && !hasReceivedAosFromRespondent(caseData);
could you leave this as `isReceivedAosFromRespondent` please

2020-12-04 10:15 UTC, madjava commented on helpers/petitionHelper.js
> +};
this construct `Boolean(hasBeenServedByAlternativeMethod(caseData) && !isPetitionerRepresented(caseData) && !hasReceivedAosFromRespondent());` is not necessary

2020-12-04 10:17 UTC, madjava commented on helpers/petitionHelper.js
> +};
i suggest:

`const isServedByAlternativeMethod = caseData => {
   if(isPetitionerRepresented(caseData)) {
     return false;
   }
  return isBeenServedByAlternativeMethod(caseData) && !isReceivedAosFromRespondent();
};`

2020-12-04 10:32 UTC, madjava commented on test/unit/steps/petitionerProgressBar.test.js
> +            permittedDecreeNisiReason: '8'
Actual number of `permittedDecreeNisiReason` are not up to 8, if you make this number say 2, what happens with your test.

2020-12-04 10:36 UTC, madjava commented
Any possibility of covering a few negative scenarios in. the test case, even if just the core ones such as when `servedByAlternativeMethod` is `No` but `receivedAosFromResp` is `Yes` and a different DNReason exists.

2020-12-04 10:46 UTC, madjava commented on steps/petition-progress-bar/sections/servedByAlternativeMethod/PetitionProgressBar.content.servedByAlternativeMethod.json
> +}
For the `cy` sections could you start the sentence with `[CY]` prefix so this this is very obvious if a user switches language on the frontend. e.g. `"servedByAlternativeMethodStatusMsg": "[CY] Your divorce petition has been served by...`

2020-12-04 10:50 UTC, madjava commented on helpers/petitionHelper.js
> +};
Also `isBeenServedByAlternativeMethod` should be `isServedByAlternativeMethod `

2020-12-04 11:01 UTC, madjava commented on test/unit/helpers/petitionHelper.test.js
> +  describe('Served by alternative method: ', () => {
Nice, positive scenario covered here. Do add other scenarios as per AC's so you are sure the current/default behaviour for DN related cases still holds.

2020-12-04 11:03 UTC, madjava commented on test/unit/steps/petitionerProgressBar.test.js
> +
If: 
`servedByAlternativeMethod: 'No',
  receivedAosFromResp: 'Yes',
  permittedDecreeNisiReason: '2'`

What happens?

2020-12-04 11:14 UTC, jacmurphy commented on test/unit/steps/petitionerProgressBar.test.js
> +
This PR was from a few days ago where i had only covered AC1. As i cover 2 and 3 ill flesh out some other scenarios, like youve pointed out. I just put this up as i did so that id have suggestions and recommendations for when i came back

2020-12-04 11:15 UTC, jacmurphy commented on test/unit/helpers/petitionHelper.test.js
> +  describe('Served by alternative method: ', () => {
Thank you Felix. Im glad you pointed that out. Theyre work in progress ATM

2020-12-04 11:17 UTC, jacmurphy commented on test/unit/steps/petitionerProgressBar.test.js
> +            permittedDecreeNisiReason: '8'
Where did you find that information? I had actually thought it was to do with 
```
const permitDNReasonMap = new Map([
.....
  ['6', './sections/dispensedApproved/PetitionProgressBar.dispensedApproved.template.html'],
  ['7', './sections/processServerService/PetitionProgressBar.processServerService.template.html'],
  ['8', './sections/servedByAlternativeMethod/PetitionProgressBar.servedByAlternativeMethod.template.html']
]);
```
I added the 8th scenario, so i believed 8 was okay. Am i misunderstanding this?

2020-12-04 12:01 UTC, jacmurphy commented on helpers/petitionHelper.js
> +};
I dont see much of a difference between these two options @madjava. 
Could you elaborate on how it would be improved by the way you've described?

2020-12-04 12:04 UTC, jacmurphy commented on helpers/petitionHelper.js
> +  isReceivedAosFromRespondent: hasReceivedAosFromRespondent,
Thankfully `has` is as valid as `is` when representing a boolean as it is a descriptive possessive term. Which is what a boolean needs. Has reads better in this context

2020-12-04 12:06 UTC, jacmurphy commented on steps/petition-progress-bar/sections/servedByAlternativeMethod/PetitionProgressBar.content.servedByAlternativeMethod.json
> +}
Thats a fantastic suggestion felix. Ill do that now

2020-12-04 12:18 UTC, jacmurphy commented on helpers/petitionHelper.js
> +  return isServedByProcessServer(caseData) && !hasReceivedAosFromRespondent(caseData);
I dont believe that `isReceivedAosFromRespondent` is correct english. And seeing as `has` is a valid preface for a boolean, i see this as a readability improvement

2020-12-07 10:12 UTC, madjava commented on test/unit/steps/petitionerProgressBar.test.js
> +            permittedDecreeNisiReason: '8'
There would never be a  `permittedDecreeNisiReason` that is 8 when served by process server. The value `permittedDecreeNisiReason` is set when the case was initially created and there are only about 5 possible options.

2020-12-07 10:14 UTC, madjava commented on test/unit/steps/petitionerProgressBar.test.js
> +            permittedDecreeNisiReason: '8'
There would never be a `permittedDecreeNisiReason` that is 8 if served by process server

2020-12-07 10:23 UTC, madjava commented on helpers/petitionHelper.js
> +};
1. Its too completed
2. once `!isPetitionerRepresented(caseData)` which is a key reason to proceed or not is false there is no need to continue with the logic, better fo fail early, you have this right in the middle of this logic
3. If for any reason any of this methods you have chained in this construct returns any other value, this `Boolean` would still try to evaluate it to true or false. Try `Boolean(" ")` in your console and see the out put

2020-12-07 10:23 UTC, yarpo commented on helpers/petitionHelper.js
> +};
I think the issue here is the difference between `Boolean` object-wrapper and `boolean` primitive type in Javascript.

Since `Boolean` is an object it may have 3 values:
- null
- instance of `Boolean` object with value `true`
- instance of `Boolean` object with value `false`

What is more according to javascript comparisons in `if`s you can get:

<img width="605" alt="Screenshot 2020-12-07 at 11 17 09" src="https://user-images.githubusercontent.com/5647337/101338815-c90be700-387d-11eb-9b4e-166abbfe15ff.png">

Which is confusing. 

`Boolean` used as method to cast value to `boolean` works differently than `Boolean` used as a constructor of `Boolean` object with `new` constructor.

This is why it's better/safer NOT to use it at all. In fact, back in the past, operator `new` was working so weird it was advice not to be used.

https://web.archive.org/web/20121107121625/http://www.yuiblog.com/blog/2006/11/13/javascript-we-hardly-new-ya/

2020-12-07 10:35 UTC, madjava commented on helpers/petitionHelper.js
> +  isReceivedAosFromRespondent: hasReceivedAosFromRespondent,
@jacmurphy i still go with the `is` prefix here not that `has` is not valid. Here however internally you have called this method  `hasReceivedAosFromRespondent` but you are still exposing `isReceivedAosFromRespondent`.  I think you should keep it uniformed.

2020-12-07 11:58 UTC, madjava commented on test/unit/helpers/petitionHelper.test.js
> +  });
Nice! 👌🏾

2020-12-07 11:59 UTC, madjava commented on test/unit/steps/petitionerProgressBar.test.js
> +   */
Rogue comment!!! Blocker 😜

2020-12-07 12:11 UTC, yarpo approved these changes

2020-12-07 13:03 UTC, jacmurphy commented on test/unit/steps/petitionerProgressBar.test.js
> +   */
Youre 100% right. I thought i had removed this in the latest commit. Good spot

2020-12-07 13:26 UTC, madjava requested changes
This still needs to be aligned `isReceivedAosFromRespondent: hasReceivedAosFromRespondent,` so we are clear which one it is, else you name update to `hasXXX` is not captured outside of this module. All external users of this module will still be using `isXXX`. Have a look

2020-12-07 14:34 UTC, madjava commented on helpers/petitionHelper.js
> +  const isServedByAlternativeMethodValid = Boolean(hasBeenServedByAlternativeMethod(caseData) && !isPetitionerRepresented(caseData) && !isReceivedAosFromRespondent(caseData));
Please update this Jack, don't use this `Boolean` construct.

2020-12-07 14:35 UTC, jacmurphy commented on helpers/petitionHelper.js
> +  const isServedByAlternativeMethodValid = Boolean(hasBeenServedByAlternativeMethod(caseData) && !isPetitionerRepresented(caseData) && !isReceivedAosFromRespondent(caseData));
Im not sure why this needs to be changed.
My understanding is that it forces a truthy statement. What is wrong with this approach ?

2020-12-07 15:54 UTC, jacmurphy commented on helpers/petitionHelper.js
> +};
Updated with @madjava 's mentorship

2020-12-07 15:58 UTC, madjava approved these changes

2020-12-07 16:10 UTC, jacmurphy commented on helpers/petitionHelper.js
> +  const isServedByAlternativeMethodValid = Boolean(hasBeenServedByAlternativeMethod(caseData) && !isPetitionerRepresented(caseData) && !isReceivedAosFromRespondent(caseData));
We discussed this on a call and i see where Felix was coming from and agree with his assesment. I have updated logic accordingly

2020-12-09 10:33 UTC, madjava commented
Merging these changes in. Can't be tested from a PR

2020-12-09 10:34 UTC, merged